services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: salman
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: madalasalman95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: salman
      PGADMIN_DEFAULT_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-networks
      - postgres

networks:
  microservice-networks:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: